name: FeatureAction

# on: 
#   push:
#     branches:
#       - feature/**
#       - fix/**

# jobs:
#   test:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@master
#       with:
#         persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
#         fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
        
#     - name: Run Test 
#       run: |
#         sh bash-sh.sh

on: 
  pull_request_review_comment:
    types:
      - create

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.comment.body == 'Test This.'
    steps:
      - name: delete branch
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{github.token}}
          branches: test

      - name: create branch
        uses: peterjgrainger/action-create-branch@v1.0.0
        with:
          branch: 'test'
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
